### ISSUE TITLE
Makefile.dist and Makefile from configure produce different executables

### ISSUE THREAD

**Issue by dbeeman** [borismarin/genesis2.4gamma#20]
The 'genesis' executable produced when using configure is about 10% larger than that produced when using Makefile.dist. Could different CFLAGS give different levels of optimization?

**Comment by physicalist** [comment]
My assumption is rather that this is mainly due to two additional X-related libraries being linked: `SM` and `ICE`. Autoconf automatically replaces `@X_PRE_LIBS@` with `-lSM -lICE`, which was incidentally what caused `netcdf` to fail building on OSX. See my fix in 2ececad701cbc8696eb3d93bd6279663b9bd427b.

Could someone test what happens if you commented out the line `XPRELIBS=@X_PRE_LIBS@` in `Makefile.in` (line 34)? If the file sizes still differ (probably by less than 10% though), it could indeed be because of different optimisations.
I'm not sure why those libraries are linked at all since it seems to build & work fine without. @borismarin, why did you include `@X_PRE_LIBS@`?

**Comment by physicalist** [comment]
Oh wow, I did not see that coming!

GENESIS compiled via autoconf...
- with `CFLAGS=-O2 make`: `-rwxr-xr-x  1 janpi  staff  3537376 Nov  7 09:56 genesis`
- without optimisations: `-rwxr-xr-x  1 janpi  staff  5249868 Nov  7 09:51 genesis`

The difference is quit a bit bigger than I expected! Maybe the additional libraries don't make a difference, could someone please confirm that?

I think we should default to `-O2` anyway, at least the Linux & Darwin builds in the original Makefile.dist did so anyway.

Compiling via the legacy Makefile with `-O2` was actually a bit bigger than with autoconf in my case, but then again it linked ncurses instead of curses and used cc instead of gcc (both Apple), so it becomes hard to say what's causing what :)
Do we really need to ensure both build systems produce bitwise-identical binaries?

EDIT: I accidentally switched the ls snippets around, the more optimised binary is also a lot smaller, not bigger!

**Comment by borismarin** [comment]
Wouldn't it be more useful running some tests (à la rallpack for the numerics, but potentially extensible to control/io/gui stuff as well) to make sure that the binaries are behaving correctly?

**Comment by physicalist** [comment]
Yes it would. I'd argue that they should behave correctly though on account of `-O2` being the standard "conservative" optimisation, and was used in GENESIS since at least its last release ca. 2003. Unless Genesis has been calculating incorrectly ever since, but I doubt `-O2` would cause issues here.

But it never hurts to be sure!

**Comment by physicalist** [comment]
Oh, and as for the GUI elements etc., I doubt that there will be problems if there are no complaints at build time. Still, any idea how to test this? I have only rudimentary experience with the GUI capabilities, I only use it to monitor the cell's membrane potential as the simulation runs.

**Comment by dbeeman** [comment]
Of course, the increased size is not an issue. These days, 4 MB is nothing. I am more concerned with speed and accuracy. I think that -lSm and -lICE were used needed on some very early versions of Linux, but have not been needed for a long time.  Are they needed for Darwin?

I'll address the accuracy tests separately, and resurrect some instructions that I had for the 2.3 beta.
the rallpack axon.g test is a good one, and some tests should be made to see if SPRNG gives the same random numbers.

**Comment by physicalist** [comment]
I removed libSM & libICE from the configure builds in af6b98801e1fdbedba000015e721ef34de661860. In current versions of Darwin (after switch from ppc to Intel), they're not only not needed but prevent netcdf from building properly, see #16.
